# Generated by Django 5.1.3 on 2024-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Временная метка"
                    ),
                ),
                (
                    "usd_to_rub",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Курс доллара к рублю",
                    ),
                ),
            ],
        ),
    ]
